name: whatever-dev

services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama-dev
    volumes:
      - ollama-dev:/root/.ollama
    networks:
      - whatever_network_dev
    ports:
      - "11434:11434"
    restart: unless-stopped

  whatever:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OLLAMA_BASE_URL: '/ollama'
    image: ghcr.io/whatever/whatever:${WEBUI_DOCKER_TAG-main}
    container_name: whatever-dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - OLLAMA_BASE_URL=http://ollama-dev:11434
    volumes:
      - whatever-dev:/app/data
    ports:
      - "3000:8080"
    depends_on:
      - ollama
      - backend
    networks:
      - whatever_network_dev
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatever-backend-dev
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - HOST=0.0.0.0
      - PORT=8080
      - OLLAMA_BASE_URL=http://ollama-dev:11434
      - SKIP_CHANGELOG=true
      - SKIP_FFMPEG=true
      - CHANGELOG_CONTENT="{}"
    volumes:
      - whatever-backend-dev:/app/data
    ports:
      - "8080:8080"
    networks:
      - whatever_network_dev
    depends_on:
      - ollama
    restart: unless-stopped
    entrypoint: ["/bin/bash"]
    command: ["start.sh"]

volumes:
  ollama-dev:
  whatever-dev:
  whatever-backend-dev:

networks:
  whatever_network_dev:
    driver: bridge